name: analisi_dades
channels:
          - defaults
dependencies:
          - pip=20.2.4
          - python=3.7.9
          - pip:
                - jupyter==1.0.0
                - numpy==1.19.3
                - pandas==1.1.4
